# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/deviceonly.proto

require 'google/protobuf'

require 'meshtastic/channel_pb'
require 'meshtastic/mesh_pb'
require 'meshtastic/telemetry_pb'
require 'meshtastic/config_pb'
require 'meshtastic/localonly_pb'
require 'nanopb_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/deviceonly.proto", :syntax => :proto3) do
    add_message "meshtastic.PositionLite" do
      optional :latitude_i, :sfixed32, 1
      optional :longitude_i, :sfixed32, 2
      optional :altitude, :int32, 3
      optional :time, :fixed32, 4
      optional :location_source, :enum, 5, "meshtastic.Position.LocSource"
    end
    add_message "meshtastic.UserLite" do
      optional :macaddr, :bytes, 1
      optional :long_name, :string, 2
      optional :short_name, :string, 3
      optional :hw_model, :enum, 4, "meshtastic.HardwareModel"
      optional :is_licensed, :bool, 5
      optional :role, :enum, 6, "meshtastic.Config.DeviceConfig.Role"
      optional :public_key, :bytes, 7
    end
    add_message "meshtastic.NodeInfoLite" do
      optional :num, :uint32, 1
      optional :user, :message, 2, "meshtastic.UserLite"
      optional :position, :message, 3, "meshtastic.PositionLite"
      optional :snr, :float, 4
      optional :last_heard, :fixed32, 5
      optional :device_metrics, :message, 6, "meshtastic.DeviceMetrics"
      optional :channel, :uint32, 7
      optional :via_mqtt, :bool, 8
      proto3_optional :hops_away, :uint32, 9
      optional :is_favorite, :bool, 10
      optional :is_ignored, :bool, 11
      optional :next_hop, :uint32, 12
    end
    add_message "meshtastic.DeviceState" do
      optional :my_node, :message, 2, "meshtastic.MyNodeInfo"
      optional :owner, :message, 3, "meshtastic.User"
      repeated :receive_queue, :message, 5, "meshtastic.MeshPacket"
      optional :version, :uint32, 8
      optional :rx_text_message, :message, 7, "meshtastic.MeshPacket"
      optional :no_save, :bool, 9
      optional :did_gps_reset, :bool, 11
      optional :rx_waypoint, :message, 12, "meshtastic.MeshPacket"
      repeated :node_remote_hardware_pins, :message, 13, "meshtastic.NodeRemoteHardwarePin"
    end
    add_message "meshtastic.NodeDatabase" do
      optional :version, :uint32, 1
      repeated :nodes, :message, 2, "meshtastic.NodeInfoLite"
    end
    add_message "meshtastic.ChannelFile" do
      repeated :channels, :message, 1, "meshtastic.Channel"
      optional :version, :uint32, 2
    end
    add_message "meshtastic.BackupPreferences" do
      optional :version, :uint32, 1
      optional :timestamp, :fixed32, 2
      optional :config, :message, 3, "meshtastic.LocalConfig"
      optional :module_config, :message, 4, "meshtastic.LocalModuleConfig"
      optional :channels, :message, 5, "meshtastic.ChannelFile"
      optional :owner, :message, 6, "meshtastic.User"
    end
  end
end

module Meshtastic
  PositionLite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PositionLite").msgclass
  UserLite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.UserLite").msgclass
  NodeInfoLite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeInfoLite").msgclass
  DeviceState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.DeviceState").msgclass
  NodeDatabase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeDatabase").msgclass
  ChannelFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ChannelFile").msgclass
  BackupPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.BackupPreferences").msgclass
end
