# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/deviceonly_legacy.proto

require 'google/protobuf'

require 'meshtastic/deviceonly_pb'
require 'meshtastic/telemetry_pb'
require 'nanopb_pb'


descriptor_data = "\n\"meshtastic/deviceonly_legacy.proto\x12\nmeshtastic\x1a\x1bmeshtastic/deviceonly.proto\x1a\x1ameshtastic/telemetry.proto\x1a\x0cnanopb.proto\"\xdc\x02\n\x13NodeInfoLite_Legacy\x12\x0b\n\x03num\x18\x01 \x01(\r\x12\"\n\x04user\x18\x02 \x01(\x0b\x32\x14.meshtastic.UserLite\x12*\n\x08position\x18\x03 \x01(\x0b\x32\x18.meshtastic.PositionLite\x12\x0b\n\x03snr\x18\x04 \x01(\x02\x12\x12\n\nlast_heard\x18\x05 \x01(\x07\x12\x31\n\x0e\x64\x65vice_metrics\x18\x06 \x01(\x0b\x32\x19.meshtastic.DeviceMetrics\x12\x0f\n\x07\x63hannel\x18\x07 \x01(\r\x12\x10\n\x08via_mqtt\x18\x08 \x01(\x08\x12\x16\n\thops_away\x18\t \x01(\rH\x00\x88\x01\x01\x12\x13\n\x0bis_favorite\x18\n \x01(\x08\x12\x12\n\nis_ignored\x18\x0b \x01(\x08\x12\x10\n\x08next_hop\x18\x0c \x01(\r\x12\x10\n\x08\x62itfield\x18\r \x01(\rB\x0c\n\n_hops_away\"\x89\x01\n\x13NodeDatabase_Legacy\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x61\n\x05nodes\x18\x02 \x03(\x0b\x32\x1f.meshtastic.NodeInfoLite_LegacyB1\x92?.\x92\x01+std::vector<meshtastic_NodeInfoLite_Legacy>Bt\n\x14org.meshtastic.protoB\x10\x44\x65viceOnlyLegacyZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x92?\x0b\xc2\x01\x08<vector>b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Meshtastic
  NodeInfoLite_Legacy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeInfoLite_Legacy").msgclass
  NodeDatabase_Legacy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeDatabase_Legacy").msgclass
end
