# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/interdevice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/interdevice.proto", :syntax => :proto3) do
    add_message "meshtastic.SensorData" do
      optional :type, :enum, 1, "meshtastic.MessageType"
      oneof :data do
        optional :float_value, :float, 2
        optional :uint32_value, :uint32, 3
      end
    end
    add_message "meshtastic.InterdeviceMessage" do
      oneof :data do
        optional :nmea, :string, 1
        optional :sensor, :message, 2, "meshtastic.SensorData"
      end
    end
    add_enum "meshtastic.MessageType" do
      value :ACK, 0
      value :COLLECT_INTERVAL, 160
      value :BEEP_ON, 161
      value :BEEP_OFF, 162
      value :SHUTDOWN, 163
      value :POWER_ON, 164
      value :SCD41_TEMP, 176
      value :SCD41_HUMIDITY, 177
      value :SCD41_CO2, 178
      value :AHT20_TEMP, 179
      value :AHT20_HUMIDITY, 180
      value :TVOC_INDEX, 181
    end
  end
end

module Meshtastic
  SensorData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SensorData").msgclass
  InterdeviceMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.InterdeviceMessage").msgclass
  MessageType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.MessageType").enummodule
end
