# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh_beacon.proto

require 'google/protobuf'

require 'meshtastic/channel_pb'
require 'meshtastic/config_pb'


descriptor_data = "\n\x1cmeshtastic/mesh_beacon.proto\x12\nmeshtastic\x1a\x18meshtastic/channel.proto\x1a\x17meshtastic/config.proto\"\xe8\x01\n\nMeshBeacon\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x32\n\roffer_channel\x18\x02 \x01(\x0b\x32\x1b.meshtastic.ChannelSettings\x12>\n\x0coffer_region\x18\x03 \x01(\x0e\x32(.meshtastic.Config.LoRaConfig.RegionCode\x12\x44\n\x0coffer_preset\x18\x04 \x01(\x0e\x32).meshtastic.Config.LoRaConfig.ModemPresetH\x00\x88\x01\x01\x42\x0f\n\r_offer_presetBf\n\x14org.meshtastic.protoB\x10MeshBeaconProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Meshtastic
  MeshBeacon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.MeshBeacon").msgclass
end
