# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/powermon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/powermon.proto", :syntax => :proto3) do
    add_message "meshtastic.PowerMon" do
    end
    add_enum "meshtastic.PowerMon.State" do
      value :None, 0
      value :CPU_DeepSleep, 1
      value :CPU_LightSleep, 2
      value :Vext1_On, 4
      value :Lora_RXOn, 8
      value :Lora_TXOn, 16
      value :Lora_RXActive, 32
      value :BT_On, 64
      value :LED_On, 128
      value :Screen_On, 256
      value :Screen_Drawing, 512
      value :Wifi_On, 1024
      value :GPS_Active, 2048
    end
    add_message "meshtastic.PowerStressMessage" do
      optional :cmd, :enum, 1, "meshtastic.PowerStressMessage.Opcode"
      optional :num_seconds, :float, 2
    end
    add_enum "meshtastic.PowerStressMessage.Opcode" do
      value :UNSET, 0
      value :PRINT_INFO, 1
      value :FORCE_QUIET, 2
      value :END_QUIET, 3
      value :SCREEN_ON, 16
      value :SCREEN_OFF, 17
      value :CPU_IDLE, 32
      value :CPU_DEEPSLEEP, 33
      value :CPU_FULLON, 34
      value :LED_ON, 48
      value :LED_OFF, 49
      value :LORA_OFF, 64
      value :LORA_TX, 65
      value :LORA_RX, 66
      value :BT_OFF, 80
      value :BT_ON, 81
      value :WIFI_OFF, 96
      value :WIFI_ON, 97
      value :GPS_OFF, 112
      value :GPS_ON, 113
    end
  end
end

module Meshtastic
  PowerMon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PowerMon").msgclass
  PowerMon::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PowerMon.State").enummodule
  PowerStressMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PowerStressMessage").msgclass
  PowerStressMessage::Opcode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PowerStressMessage.Opcode").enummodule
end
