# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/serial_hal.proto

require 'google/protobuf'


descriptor_data = "\n\x1bmeshtastic/serial_hal.proto\x12\nmeshtastic\"\xa2\x02\n\x10SerialHalCommand\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.meshtastic.SerialHalCommand.Type\x12\x0b\n\x03pin\x18\x03 \x01(\r\x12\r\n\x05value\x18\x04 \x01(\r\x12\x0c\n\x04mode\x18\x05 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"\x8c\x01\n\x04Type\x12\t\n\x05UNSET\x10\x00\x12\x0c\n\x08PIN_MODE\x10\x01\x12\x11\n\rDIGITAL_WRITE\x10\x02\x12\x10\n\x0c\x44IGITAL_READ\x10\x03\x12\x14\n\x10\x41TTACH_INTERRUPT\x10\x04\x12\x14\n\x10\x44\x45TACH_INTERRUPT\x10\x05\x12\x10\n\x0cSPI_TRANSFER\x10\x06\x12\x08\n\x04NOOP\x10\x07\"\xcc\x01\n\x11SerialHalResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\r\x12\x34\n\x06result\x18\x02 \x01(\x0e\x32$.meshtastic.SerialHalResponse.Result\x12\r\n\x05value\x18\x03 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"=\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x02\x12\x0f\n\x0bUNSUPPORTED\x10\x03\x42_\n\x14org.meshtastic.protoB\tSerialHalZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Meshtastic
  SerialHalCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SerialHalCommand").msgclass
  SerialHalCommand::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SerialHalCommand.Type").enummodule
  SerialHalResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SerialHalResponse").msgclass
  SerialHalResponse::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SerialHalResponse.Result").enummodule
end
